cd "d:/K210Project/standalone/LCD/build"
SET ALLUSERSPROFILE=C:\ProgramData
SET AMDRMPATH=C:\Program Files\AMD\RyzenMaster\
SET APPDATA=C:\Users\nj055\AppData\Roaming
SET asl.log=Destination=file
SET CARBON_MEM_DISABLE=1
SET CommonProgramFiles=C:\Program Files\Common Files
SET CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
SET CommonProgramW6432=C:\Program Files\Common Files
SET COMPUTERNAME=DESKTOP-B21K015
SET ComSpec=C:\WINDOWS\system32\cmd.exe
SET DriverData=C:\Windows\System32\Drivers\DriverData
SET FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
SET FPS_BROWSER_USER_PROFILE_STRING=Default
SET HOMEDRIVE=C:
SET HOMEPATH=\Users\nj055
SET KENDRYTE_IDE_LOCAL_PACKAGE_DIR=H:\K210IDE\KendryteIDE\LocalPackage
SET KENDRYTE_IDE_UPDATER=H:\K210IDE\KendryteIDE\Updater\electron.exe
SET KENDRYTE_IDE_UPDATER_CONTENT_ROOT=H:\K210IDE\KendryteIDE
SET KENDRYTE_IDE_UPDATER_IS_BUILT=yes
SET KENDRYTE_IDE_UPDATER_PIPE=\\?\pipe\C:\Users\nj055\AppData\Local\Temp\KendryteIDE_Cache\22161_updater.sock
SET KENDRYTE_IDE_UPDATER_PIPE_ID=1
SET LOCALAPPDATA=C:\Users\nj055\AppData\Local
SET LOGONSERVER=\\DESKTOP-B21K015
SET NUMBER_OF_PROCESSORS=12
SET OneDrive=C:\Users\nj055\OneDrive
SET OneDriveConsumer=C:\Users\nj055\OneDrive
SET OS=Windows_NT
SET Path=h:\K210IDE\KendryteIDE\bin;H:\K210IDE\KendryteIDE\LocalPackage\toolchain\bin;H:\K210IDE\KendryteIDE\LocalPackage\cmake\bin;H:\K210IDE\KendryteIDE\LocalPackage\jlink;H:\K210IDE\KendryteIDE\LocalPackage\clang-format\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH
SET PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
SET PROCESSOR_ARCHITECTURE=AMD64
SET PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
SET PROCESSOR_LEVEL=23
SET PROCESSOR_REVISION=7100
SET ProgramData=C:\ProgramData
SET ProgramFiles=C:\Program Files
SET ProgramFiles(x86)=C:\Program Files (x86)
SET ProgramW6432=C:\Program Files
SET PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
SET PUBLIC=C:\Users\Public
SET PyCharm Community Edition=H:\PyCharm Community Edition 2019.2.1\bin;
SET SESSIONNAME=Console
SET SystemDrive=C:
SET SystemRoot=C:\WINDOWS
SET SYSTEM_TEMP=C:\Users\nj055\AppData\Local\Temp
SET TEMP=C:\Users\nj055\AppData\Local\Temp\KendryteIDE_Cache
SET TMP=C:\Users\nj055\AppData\Local\Temp\KendryteIDE_Cache
SET TMPDIR=C:\Users\nj055\AppData\Local\Temp\KendryteIDE_Cache
SET USERDOMAIN=DESKTOP-B21K015
SET USERDOMAIN_ROAMINGPROFILE=DESKTOP-B21K015
SET USERNAME=nj055
SET USERPROFILE=C:\Users\nj055
SET VS160COMCOMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\
SET VSCODE_CWD=C:\WINDOWS\System32
SET VSCODE_IPC_HOOK=\\.\pipe\0da2c7487f4aecd0538079a4c4ec170b-1.34.1-beta-main-sock
SET VSCODE_LOGS=H:\K210IDE\KendryteIDE\UserData\latest\user-data\logs\20210726T230543
SET VSCODE_NLS_CONFIG={"locale":"zh-cn","availableLanguages":{"*":"zh-cn"},"_languagePackId":"2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_translationsConfigFile":"H:\\K210IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\tcf.json","_cacheRoot":"H:\\K210IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_resolvedLanguagePackCoreLocation":"H:\\K210IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\e4de46724de34a5f46541818e9fee25971ac9969","_corruptedFile":"H:\\K210IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\corrupted.info","_languagePackSupport":true}
SET VSCODE_NODE_CACHED_DATA_DIR=H:\K210IDE\KendryteIDE\UserData\latest\user-data\CachedData\e4de46724de34a5f46541818e9fee25971ac9969
SET VSCODE_PATH=H:\K210IDE\KendryteIDE\Application\app_1.34.1-beta_20190802.2
SET VSCODE_PID=12556
SET VSCODE_PORTABLE=H:\K210IDE\KendryteIDE\UserData\latest
SET windir=C:\WINDOWS
SET PYTHONHOME=H:/K210IDE/KendryteIDE/LocalPackage/python2library
SET PYTHONPATH=H:/K210IDE/KendryteIDE/LocalPackage/python2library;H:/K210IDE/KendryteIDE/LocalPackage/toolchain/share/gdb/python
SET PYTHONDONTWRITEBYTECODE=yes
SET CMAKE_MAKE_PROGRAM=make
SET KENDRYTE_IDE=yes
SET LANG=en_US.utf-8
"H:/K210IDE/KendryteIDE/LocalPackage/cmake/bin/cmake.exe" --build d:/K210Project/standalone/LCD/build -- -j 11